### ISSUE TITLE
Runtime error on Docker instance

### ISSUE THREAD

**Issue by xaberue** [ChustaSoft/SecureConfig#38]
_Reported from [Youtube video tutorial](https://youtu.be/-7MBpqpr4ko)_

Hi, I did all the steps from de video and it worked perfectly from visual studio, but when I run it from docker i got the next error:

Unhandled exception. System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at ChustaSoft.Common.Helpers.EncryptationHelper.CreateMD5Hash(String text)
   at ChustaSoft.Common.Helpers.EncryptationHelper.Get32ByteArrayKey(String passPhrase)
   at ChustaSoft.Common.Helpers.EncryptationHelper.Encrypt(String plainText, String passPhrase)
   at ChustaSoft.Tools.SecureConfig.EncrypterManager.Encrypt[TSettings](TSettings appSettings, String privateKey)
   at ChustaSoft.Tools.SecureConfig.WebHostExtensions.GetEncryptedConfiguration[TSettings](IServiceScope scope, String settingsParamName)
   at ChustaSoft.Tools.SecureConfig.WebHostExtensions.PerformSettingsEncryption[TSettings](IServiceProvider services, String settingsParamName)
   at ChustaSoft.Tools.SecureConfig.WebHostExtensions.EncryptSettings[TSettings](IHost host, Boolean encrypt, String settingsParamName)
   at Solution.API.Program.Main(String[] args) in /src/Services/Core/API/Core.API/Program.cs:line 13

the line 13 is:
 CreateHostBuilder(args)
                .Build()
                .EncryptSettings<AppSettings>(true)
                .Run();
I comment the line .EncryptSettings<AppSettings>(true)
 and the error disappears but the encryption doesn't work

Do you know how to solve this issue?

**Comment by xaberue** [comment]
Seems a problem trying to get the private key from the Environment variables. 

Has this key been added as a container runtime variable?

Check this [link](https://stackify.com/docker-environment-variables/#:~:text=Docker%20environment%20variables%20are%20key%20elements%20in%20this,command%20line%20interface%20(CLI)%20or%20an%20external)

**Comment by hidarraga** [comment]
Hi, yes the problem was that i didn't add the SECRET_KEY on the environment variables, now it's working fine, thanks.

**Comment by xaberue** [comment]
Hi @hidarraga !

Thanks for raise the question, I will close the question then.

Best regards :)
