### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by venkatpoluri** [ChustaSoft/SecureConfig#53]
![image](https://github.com/ChustaSoft/SecureConfig/assets/16118198/94a97915-9cac-4bae-90a0-94a2ad570333)
I'm trying to use this Nuget package in ASP.Net MVC Core TFM 6.0, it is throwing the below error.
Can you please provide assistance.
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ChustaSoft.Tools.SecureConfig
  StackTrace:
   at ChustaSoft.Tools.SecureConfig.SettingsConverter.Get[TSettings](String filePath, String sectionName)
   at ChustaSoft.Tools.SecureConfig.IServiceProviderExtensions.GetEncryptedConfiguration[TSettings](IServiceScope scope, IWritableSettings`1 writableSettings)
   at ChustaSoft.Tools.SecureConfig.IServiceProviderExtensions.PerformSettingsEncryption[TSettings](IServiceProvider services, String settingsParamName)
   at ChustaSoft.Tools.SecureConfig.WebHostExtensions.EncryptSettings[TSettings](WebApplication webApplication, Boolean encrypt, String settingsParamName)

**Comment by venkatpoluri** [comment]
AppSettings not available in Environment wise Appsettings.json
